// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7PiA-wl_uEYXLs2wDVZCl791rfxFlggo',
    appId: '1:423747164232:android:a175edaa2bd000a7ee607d',
    messagingSenderId: '423747164232',
    projectId: 'mivafid-1bc6a',
    storageBucket: 'mivafid-1bc6a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBFhYCnwmc4BwBTcal5FbyT4hqxz-raTM',
    appId: '1:423747164232:ios:14973c0821085216ee607d',
    messagingSenderId: '423747164232',
    projectId: 'mivafid-1bc6a',
    storageBucket: 'mivafid-1bc6a.firebasestorage.app',
    androidClientId: '423747164232-j5glla77ht18qboe5vfd8ar29466rcl9.apps.googleusercontent.com',
    iosClientId: '423747164232-6mppmco5mi8mbeelp4v7l2agus3tk598.apps.googleusercontent.com',
    iosBundleId: 'com.example.fidelityApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuVrtat-zPs0dWMIBlv0ZlaSCVuokRCew',
    appId: '1:423747164232:web:d7b31e3d73f3caf6ee607d',
    messagingSenderId: '423747164232',
    projectId: 'mivafid-1bc6a',
    authDomain: 'mivafid-1bc6a.firebaseapp.com',
    storageBucket: 'mivafid-1bc6a.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBFhYCnwmc4BwBTcal5FbyT4hqxz-raTM',
    appId: '1:423747164232:ios:14973c0821085216ee607d',
    messagingSenderId: '423747164232',
    projectId: 'mivafid-1bc6a',
    storageBucket: 'mivafid-1bc6a.firebasestorage.app',
    androidClientId: '423747164232-j5glla77ht18qboe5vfd8ar29466rcl9.apps.googleusercontent.com',
    iosClientId: '423747164232-6mppmco5mi8mbeelp4v7l2agus3tk598.apps.googleusercontent.com',
    iosBundleId: 'com.example.fidelityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuVrtat-zPs0dWMIBlv0ZlaSCVuokRCew',
    appId: '1:423747164232:web:1c17a6010066512cee607d',
    messagingSenderId: '423747164232',
    projectId: 'mivafid-1bc6a',
    authDomain: 'mivafid-1bc6a.firebaseapp.com',
    storageBucket: 'mivafid-1bc6a.firebasestorage.app',
  );
}
