class CountryInfo {
  final String name;
  final String code;
  final String dialCode;
  final String flag;

  const CountryInfo({
    required this.name,
    required this.code,
    required this.dialCode,
    required this.flag,
  });
}

// ── Pays Africains (Priorité) ────────────────────────────────────────────────
const List<CountryInfo> kAfricanCountries = [
  CountryInfo(name: 'Algérie', code: 'DZ', dialCode: '+213', flag: '🇩🇿'),
  CountryInfo(name: 'Angola', code: 'AO', dialCode: '+244', flag: '🇦🇴'),
  CountryInfo(name: 'Bénin', code: 'BJ', dialCode: '+229', flag: '🇧🇯'),
  CountryInfo(name: 'Botswana', code: 'BW', dialCode: '+267', flag: '🇧🇼'),
  CountryInfo(name: 'Burkina Faso', code: 'BF', dialCode: '+226', flag: '🇧🇫'),
  CountryInfo(name: 'Burundi', code: 'BI', dialCode: '+257', flag: '🇧🇮'),
  CountryInfo(name: 'Cameroun', code: 'CM', dialCode: '+237', flag: '🇨🇲'),
  CountryInfo(name: 'Cap-Vert', code: 'CV', dialCode: '+238', flag: '🇨🇻'),
  CountryInfo(name: 'Rép. Centrafricaine', code: 'CF', dialCode: '+236', flag: '🇨🇫'),
  CountryInfo(name: 'Comores', code: 'KM', dialCode: '+269', flag: '🇰🇲'),
  CountryInfo(name: 'Congo-Brazzaville', code: 'CG', dialCode: '+242', flag: '🇨🇬'),
  CountryInfo(name: 'Congo-Kinshasa (RDC)', code: 'CD', dialCode: '+243', flag: '🇨🇩'),
  CountryInfo(name: 'Côte d\'Ivoire', code: 'CI', dialCode: '+225', flag: '🇨🇮'),
  CountryInfo(name: 'Djibouti', code: 'DJ', dialCode: '+253', flag: '🇩🇯'),
  CountryInfo(name: 'Égypte', code: 'EG', dialCode: '+20', flag: '🇪🇬'),
  CountryInfo(name: 'Érythrée', code: 'ER', dialCode: '+291', flag: '🇪🇷'),
  CountryInfo(name: 'Eswatini', code: 'SZ', dialCode: '+268', flag: '🇸🇿'),
  CountryInfo(name: 'Éthiopie', code: 'ET', dialCode: '+251', flag: '🇪🇹'),
  CountryInfo(name: 'Gabon', code: 'GA', dialCode: '+241', flag: '🇬🇦'),
  CountryInfo(name: 'Gambie', code: 'GM', dialCode: '+220', flag: '🇬🇲'),
  CountryInfo(name: 'Ghana', code: 'GH', dialCode: '+233', flag: '🇬🇭'),
  CountryInfo(name: 'Guinée', code: 'GN', dialCode: '+224', flag: '🇬🇳'),
  CountryInfo(name: 'Guinée-Bissau', code: 'GW', dialCode: '+245', flag: '🇬🇼'),
  CountryInfo(name: 'Guinée équatoriale', code: 'GQ', dialCode: '+240', flag: '🇬🇶'),
  CountryInfo(name: 'Kenya', code: 'KE', dialCode: '+254', flag: '🇰🇪'),
  CountryInfo(name: 'Lesotho', code: 'LS', dialCode: '+266', flag: '🇱🇸'),
  CountryInfo(name: 'Libéria', code: 'LR', dialCode: '+231', flag: '🇱🇷'),
  CountryInfo(name: 'Libye', code: 'LY', dialCode: '+218', flag: '🇱🇾'),
  CountryInfo(name: 'Madagascar', code: 'MG', dialCode: '+261', flag: '🇲🇬'),
  CountryInfo(name: 'Malawi', code: 'MW', dialCode: '+265', flag: '🇲🇼'),
  CountryInfo(name: 'Mali', code: 'ML', dialCode: '+223', flag: '🇲🇱'),
  CountryInfo(name: 'Maroc', code: 'MA', dialCode: '+212', flag: '🇲🇦'),
  CountryInfo(name: 'Maurice', code: 'MU', dialCode: '+230', flag: '🇲🇺'),
  CountryInfo(name: 'Mauritanie', code: 'MR', dialCode: '+222', flag: '🇲🇷'),
  CountryInfo(name: 'Mozambique', code: 'MZ', dialCode: '+258', flag: '🇲🇿'),
  CountryInfo(name: 'Namibie', code: 'NA', dialCode: '+264', flag: '🇳🇦'),
  CountryInfo(name: 'Niger', code: 'NE', dialCode: '+227', flag: '🇳🇪'),
  CountryInfo(name: 'Nigeria', code: 'NG', dialCode: '+234', flag: '🇳🇬'),
  CountryInfo(name: 'Ouganda', code: 'UG', dialCode: '+256', flag: '🇺🇬'),
  CountryInfo(name: 'Rwanda', code: 'RW', dialCode: '+250', flag: '🇷🇼'),
  CountryInfo(name: 'Sao Tomé-et-Principe', code: 'ST', dialCode: '+239', flag: '🇸🇹'),
  CountryInfo(name: 'Sénégal', code: 'SN', dialCode: '+221', flag: '🇸🇳'),
  CountryInfo(name: 'Seychelles', code: 'SC', dialCode: '+248', flag: '🇸🇨'),
  CountryInfo(name: 'Sierra Leone', code: 'SL', dialCode: '+232', flag: '🇸🇱'),
  CountryInfo(name: 'Somalie', code: 'SO', dialCode: '+252', flag: '🇸🇴'),
  CountryInfo(name: 'Soudan', code: 'SD', dialCode: '+249', flag: '🇸🇩'),
  CountryInfo(name: 'Soudan du Sud', code: 'SS', dialCode: '+211', flag: '🇸🇸'),
  CountryInfo(name: 'Tanzanie', code: 'TZ', dialCode: '+255', flag: '🇹🇿'),
  CountryInfo(name: 'Tchad', code: 'TD', dialCode: '+235', flag: '🇹🇩'),
  CountryInfo(name: 'Togo', code: 'TG', dialCode: '+228', flag: '🇹🇬'),
  CountryInfo(name: 'Tunisie', code: 'TN', dialCode: '+216', flag: '🇹🇳'),
  CountryInfo(name: 'Zambie', code: 'ZM', dialCode: '+260', flag: '🇿🇲'),
  CountryInfo(name: 'Zimbabwe', code: 'ZW', dialCode: '+263', flag: '🇿🇼'),
];

// ── Reste du monde (Exemples principaux, la liste complète peut être immense) ─
const List<CountryInfo> kOtherCountries = [
  CountryInfo(name: 'Afghanistan', code: 'AF', dialCode: '+93', flag: '🇦🇫'),
  CountryInfo(name: 'Albanie', code: 'AL', dialCode: '+355', flag: '🇦🇱'),
  CountryInfo(name: 'Allemagne', code: 'DE', dialCode: '+49', flag: '🇩🇪'),
  CountryInfo(name: 'Andorre', code: 'AD', dialCode: '+376', flag: '🇦🇩'),
  CountryInfo(name: 'Antigua-et-Barbuda', code: 'AG', dialCode: '+1268', flag: '🇦🇬'),
  CountryInfo(name: 'Arabie saoudite', code: 'SA', dialCode: '+966', flag: '🇸🇦'),
  CountryInfo(name: 'Argentine', code: 'AR', dialCode: '+54', flag: '🇦🇷'),
  CountryInfo(name: 'Arménie', code: 'AM', dialCode: '+374', flag: '🇦🇲'),
  CountryInfo(name: 'Australie', code: 'AU', dialCode: '+61', flag: '🇦🇺'),
  CountryInfo(name: 'Autriche', code: 'AT', dialCode: '+43', flag: '🇦🇹'),
  CountryInfo(name: 'Azerbaïdjan', code: 'AZ', dialCode: '+994', flag: '🇦🇿'),
  CountryInfo(name: 'Bahamas', code: 'BS', dialCode: '+1242', flag: '🇧🇸'),
  CountryInfo(name: 'Bahreïn', code: 'BH', dialCode: '+973', flag: '🇧🇭'),
  CountryInfo(name: 'Bangladesh', code: 'BD', dialCode: '+880', flag: '🇧🇩'),
  CountryInfo(name: 'Barbade', code: 'BB', dialCode: '+1246', flag: '🇧🇧'),
  CountryInfo(name: 'Belgique', code: 'BE', dialCode: '+32', flag: '🇧🇪'),
  CountryInfo(name: 'Belize', code: 'BZ', dialCode: '+501', flag: '🇧🇿'),
  CountryInfo(name: 'Bhoutan', code: 'BT', dialCode: '+975', flag: '🇧🇹'),
  CountryInfo(name: 'Biélorussie', code: 'BY', dialCode: '+375', flag: '🇧🇾'),
  CountryInfo(name: 'Birmanie', code: 'MM', dialCode: '+95', flag: '🇲🇲'),
  CountryInfo(name: 'Bolivie', code: 'BO', dialCode: '+591', flag: '🇧🇴'),
  CountryInfo(name: 'Bosnie-Herzégovine', code: 'BA', dialCode: '+387', flag: '🇧🇦'),
  CountryInfo(name: 'Brésil', code: 'BR', dialCode: '+55', flag: '🇧🇷'),
  CountryInfo(name: 'Brunei', code: 'BN', dialCode: '+673', flag: '🇧🇳'),
  CountryInfo(name: 'Bulgarie', code: 'BG', dialCode: '+359', flag: '🇧🇬'),
  CountryInfo(name: 'Cambodge', code: 'KH', dialCode: '+855', flag: '🇰🇭'),
  CountryInfo(name: 'Canada', code: 'CA', dialCode: '+1', flag: '🇨🇦'),
  CountryInfo(name: 'Chili', code: 'CL', dialCode: '+56', flag: '🇨🇱'),
  CountryInfo(name: 'Chine', code: 'CN', dialCode: '+86', flag: '🇨🇳'),
  CountryInfo(name: 'Chypre', code: 'CY', dialCode: '+357', flag: '🇨🇾'),
  CountryInfo(name: 'Colombie', code: 'CO', dialCode: '+57', flag: '🇨🇴'),
  CountryInfo(name: 'Corée du Nord', code: 'KP', dialCode: '+850', flag: '🇰🇵'),
  CountryInfo(name: 'Corée du Sud', code: 'KR', dialCode: '+82', flag: '🇰🇷'),
  CountryInfo(name: 'Costa Rica', code: 'CR', dialCode: '+506', flag: '🇨🇷'),
  CountryInfo(name: 'Croatie', code: 'HR', dialCode: '+385', flag: '🇭🇷'),
  CountryInfo(name: 'Cuba', code: 'CU', dialCode: '+53', flag: '🇨🇺'),
  CountryInfo(name: 'Danemark', code: 'DK', dialCode: '+45', flag: '🇩🇰'),
  CountryInfo(name: 'Dominique', code: 'DM', dialCode: '+1767', flag: '🇩🇲'),
  CountryInfo(name: 'Équateur', code: 'EC', dialCode: '+593', flag: '🇪🇨'),
  CountryInfo(name: 'Espagne', code: 'ES', dialCode: '+34', flag: '🇪🇸'),
  CountryInfo(name: 'Estonie', code: 'EE', dialCode: '+372', flag: '🇪🇪'),
  CountryInfo(name: 'États-Unis', code: 'US', dialCode: '+1', flag: '🇺🇸'),
  CountryInfo(name: 'Fidji', code: 'FJ', dialCode: '+679', flag: '🇫🇯'),
  CountryInfo(name: 'Finlande', code: 'FI', dialCode: '+358', flag: '🇫🇮'),
  CountryInfo(name: 'France', code: 'FR', dialCode: '+33', flag: '🇫🇷'),
  CountryInfo(name: 'Géorgie', code: 'GE', dialCode: '+995', flag: '🇬🇪'),
  CountryInfo(name: 'Grèce', code: 'GR', dialCode: '+30', flag: '🇬🇷'),
  CountryInfo(name: 'Grenade', code: 'GD', dialCode: '+1473', flag: '🇬🇩'),
  CountryInfo(name: 'Guatemala', code: 'GT', dialCode: '+502', flag: '🇬🇹'),
  CountryInfo(name: 'Guyana', code: 'GY', dialCode: '+592', flag: '🇬🇾'),
  CountryInfo(name: 'Haïti', code: 'HT', dialCode: '+509', flag: '🇭🇹'),
  CountryInfo(name: 'Honduras', code: 'HN', dialCode: '+504', flag: '🇭🇳'),
  CountryInfo(name: 'Hongrie', code: 'HU', dialCode: '+36', flag: '🇭🇺'),
  CountryInfo(name: 'Inde', code: 'IN', dialCode: '+91', flag: '🇮🇳'),
  CountryInfo(name: 'Indonésie', code: 'ID', dialCode: '+62', flag: '🇮🇩'),
  CountryInfo(name: 'Irak', code: 'IQ', dialCode: '+964', flag: '🇮🇶'),
  CountryInfo(name: 'Iran', code: 'IR', dialCode: '+98', flag: '🇮🇷'),
  CountryInfo(name: 'Irlande', code: 'IE', dialCode: '+353', flag: '🇮🇪'),
  CountryInfo(name: 'Islande', code: 'IS', dialCode: '+354', flag: '🇮🇸'),
  CountryInfo(name: 'Israël', code: 'IL', dialCode: '+972', flag: '🇮🇱'),
  CountryInfo(name: 'Italie', code: 'IT', dialCode: '+39', flag: '🇮🇹'),
  CountryInfo(name: 'Jamaïque', code: 'JM', dialCode: '+1876', flag: '🇯🇲'),
  CountryInfo(name: 'Japon', code: 'JP', dialCode: '+81', flag: '🇯🇵'),
  CountryInfo(name: 'Jordanie', code: 'JO', dialCode: '+962', flag: '🇯🇴'),
  CountryInfo(name: 'Kazakhstan', code: 'KZ', dialCode: '+7', flag: '🇰🇿'),
  CountryInfo(name: 'Kirghizistan', code: 'KG', dialCode: '+996', flag: '🇰🇬'),
  CountryInfo(name: 'Kiribati', code: 'KI', dialCode: '+686', flag: '🇰🇮'),
  CountryInfo(name: 'Koweït', code: 'KW', dialCode: '+965', flag: '🇰🇼'),
  CountryInfo(name: 'Laos', code: 'LA', dialCode: '+856', flag: '🇱🇦'),
  CountryInfo(name: 'Lettonie', code: 'LV', dialCode: '+371', flag: '🇱🇻'),
  CountryInfo(name: 'Liban', code: 'LB', dialCode: '+961', flag: '🇱🇧'),
  CountryInfo(name: 'Liechtenstein', code: 'LI', dialCode: '+423', flag: '🇱🇮'),
  CountryInfo(name: 'Lituanie', code: 'LT', dialCode: '+370', flag: '🇱🇹'),
  CountryInfo(name: 'Luxembourg', code: 'LU', dialCode: '+352', flag: '🇱🇺'),
  CountryInfo(name: 'Macédoine du Nord', code: 'MK', dialCode: '+389', flag: '🇲🇰'),
  CountryInfo(name: 'Malaisie', code: 'MY', dialCode: '+60', flag: '🇲🇾'),
  CountryInfo(name: 'Maldives', code: 'MV', dialCode: '+960', flag: '🇲🇻'),
  CountryInfo(name: 'Malte', code: 'MT', dialCode: '+356', flag: '🇲🇹'),
  CountryInfo(name: 'Mexique', code: 'MX', dialCode: '+52', flag: '🇲🇽'),
  CountryInfo(name: 'Micronésie', code: 'FM', dialCode: '+691', flag: '🇫🇲'),
  CountryInfo(name: 'Moldavie', code: 'MD', dialCode: '+373', flag: '🇲🇩'),
  CountryInfo(name: 'Monaco', code: 'MC', dialCode: '+377', flag: '🇲🇨'),
  CountryInfo(name: 'Mongolie', code: 'MN', dialCode: '+976', flag: '🇲🇳'),
  CountryInfo(name: 'Monténégro', code: 'ME', dialCode: '+382', flag: '🇲🇪'),
  CountryInfo(name: 'Népal', code: 'NP', dialCode: '+977', flag: '🇳🇵'),
  CountryInfo(name: 'Nicaragua', code: 'NI', dialCode: '+505', flag: '🇳🇮'),
  CountryInfo(name: 'Norvège', code: 'NO', dialCode: '+47', flag: '🇳🇴'),
  CountryInfo(name: 'Nouvelle-Zélande', code: 'NZ', dialCode: '+64', flag: '🇳🇿'),
  CountryInfo(name: 'Oman', code: 'OM', dialCode: '+968', flag: '🇴🇲'),
  CountryInfo(name: 'Ouzbékistan', code: 'UZ', dialCode: '+998', flag: '🇺🇿'),
  CountryInfo(name: 'Pakistan', code: 'PK', dialCode: '+92', flag: '🇵🇰'),
  CountryInfo(name: 'Palaos', code: 'PW', dialCode: '+680', flag: '🇵🇼'),
  CountryInfo(name: 'Palestine', code: 'PS', dialCode: '+970', flag: '🇵🇸'),
  CountryInfo(name: 'Panama', code: 'PA', dialCode: '+507', flag: '🇵🇦'),
  CountryInfo(name: 'Papouasie-Nouvelle-Guinée', code: 'PG', dialCode: '+675', flag: '🇵🇬'),
  CountryInfo(name: 'Paraguay', code: 'PY', dialCode: '+595', flag: '🇵🇾'),
  CountryInfo(name: 'Pays-Bas', code: 'NL', dialCode: '+31', flag: '🇳🇱'),
  CountryInfo(name: 'Pérou', code: 'PE', dialCode: '+51', flag: '🇵🇪'),
  CountryInfo(name: 'Philippines', code: 'PH', dialCode: '+63', flag: '🇵🇭'),
  CountryInfo(name: 'Pologne', code: 'PL', dialCode: '+48', flag: '🇵🇱'),
  CountryInfo(name: 'Portugal', code: 'PT', dialCode: '+351', flag: '🇵🇹'),
  CountryInfo(name: 'Qatar', code: 'QA', dialCode: '+974', flag: '🇶🇦'),
  CountryInfo(name: 'Rép. Dominicaine', code: 'DO', dialCode: '+1809', flag: '🇩🇴'),
  CountryInfo(name: 'République tchèque', code: 'CZ', dialCode: '+420', flag: '🇨🇿'),
  CountryInfo(name: 'Roumanie', code: 'RO', dialCode: '+40', flag: '🇷🇴'),
  CountryInfo(name: 'Royaume-Uni', code: 'GB', dialCode: '+44', flag: '🇬🇧'),
  CountryInfo(name: 'Russie', code: 'RU', dialCode: '+7', flag: '🇷🇺'),
  CountryInfo(name: 'Saint-Kitts-et-Nevis', code: 'KN', dialCode: '+1869', flag: '🇰🇳'),
  CountryInfo(name: 'Saint-Marin', code: 'SM', dialCode: '+378', flag: '🇸🇲'),
  CountryInfo(name: 'Saint-Vincent-et-les-Grenadines', code: 'VC', dialCode: '+1784', flag: '🇻🇨'),
  CountryInfo(name: 'Sainte-Lucie', code: 'LC', dialCode: '+1758', flag: '🇱🇨'),
  CountryInfo(name: 'Salvador', code: 'SV', dialCode: '+503', flag: '🇸🇻'),
  CountryInfo(name: 'Samoa', code: 'WS', dialCode: '+685', flag: '🇼🇸'),
  CountryInfo(name: 'Serbie', code: 'RS', dialCode: '+381', flag: '🇷🇸'),
  CountryInfo(name: 'Singapour', code: 'SG', dialCode: '+65', flag: '🇸🇬'),
  CountryInfo(name: 'Slovaquie', code: 'SK', dialCode: '+421', flag: '🇸🇰'),
  CountryInfo(name: 'Slovénie', code: 'SI', dialCode: '+386', flag: '🇸🇮'),
  CountryInfo(name: 'Suède', code: 'SE', dialCode: '+46', flag: '🇸🇪'),
  CountryInfo(name: 'Suisse', code: 'CH', dialCode: '+41', flag: '🇨🇭'),
  CountryInfo(name: 'Suriname', code: 'SR', dialCode: '+597', flag: '🇸🇷'),
  CountryInfo(name: 'Syrie', code: 'SY', dialCode: '+963', flag: '🇸🇾'),
  CountryInfo(name: 'Tadjikistan', code: 'TJ', dialCode: '+992', flag: '🇹🇯'),
  CountryInfo(name: 'Thaïlande', code: 'TH', dialCode: '+66', flag: '🇹🇭'),
  CountryInfo(name: 'Timor oriental', code: 'TL', dialCode: '+670', flag: '🇹🇱'),
  CountryInfo(name: 'Tonga', code: 'TO', dialCode: '+676', flag: '🇹🇴'),
  CountryInfo(name: 'Trinité-et-Tobago', code: 'TT', dialCode: '+1868', flag: '🇹🇹'),
  CountryInfo(name: 'Turkménistan', code: 'TM', dialCode: '+993', flag: '🇹🇲'),
  CountryInfo(name: 'Turquie', code: 'TR', dialCode: '+90', flag: '🇹🇷'),
  CountryInfo(name: 'Tuvalu', code: 'TV', dialCode: '+688', flag: '🇹🇻'),
  CountryInfo(name: 'Ukraine', code: 'UA', dialCode: '+380', flag: '🇺🇦'),
  CountryInfo(name: 'Uruguay', code: 'UY', dialCode: '+598', flag: '🇺🇾'),
  CountryInfo(name: 'Vanuatu', code: 'VU', dialCode: '+678', flag: '🇻🇺'),
  CountryInfo(name: 'Venezuela', code: 'VE', dialCode: '+58', flag: '🇻🇪'),
  CountryInfo(name: 'Viêt Nam', code: 'VN', dialCode: '+84', flag: '🇻🇳'),
  CountryInfo(name: 'Yémen', code: 'YE', dialCode: '+967', flag: '🇾🇪'),
];

/// Liste combinée pour la recherche globale
final List<CountryInfo> kAllCountries = [...kAfricanCountries, ...kOtherCountries];
